# Generated by Django 5.2.17 on 2026-09-18 03:38

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('core', '0005_rename_core_academiccycle_tenant_idx_core_academ_institu_b6c182_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=50, verbose_name='designação')),
                ('default_weight', models.DecimalField(decimal_places=3, help_text='Peso por omissão na fórmula de média (0 a 1), sugerido ao configurar.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='peso por omissão')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tipo de avaliação',
                'verbose_name_plural': 'tipos de avaliação',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['institution', 'is_deleted'], name='grading_eva_institu_ad7408_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='grading_evaluationtype_unique_name_per_institution')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GradingFormulaOverride',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('weights', models.JSONField(help_text='Mapa {designação do tipo de avaliação: peso}, com soma 1 (100%).', verbose_name='pesos')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_formula_overrides', to='academic.course', verbose_name='curso')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_formula_overrides', to='academic.subject', verbose_name='disciplina')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sobreposição da fórmula de média',
                'verbose_name_plural': 'sobreposições da fórmula de média',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['institution', 'is_deleted'], name='grading_gra_institu_e88906_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('institution', 'course'), name='grading_formulaoverride_one_per_course'), models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('institution', 'subject'), name='grading_formulaoverride_one_per_subject')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
