# Generated by Django 5.2.17 on 2026-09-18 19:36

from django.core.management import call_command
from django.db import migrations, models


def load_grading_scale_fixture(apps, schema_editor):
    call_command("loaddata", "grading_scale", app_label="grading")


def unload_grading_scale_fixture(apps, schema_editor):
    apps.get_model("grading", "GradingScale").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('level', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='nível')),
                ('qualitative_level', models.CharField(max_length=20, unique=True, verbose_name='nível qualitativo')),
                ('min_value', models.PositiveSmallIntegerField(verbose_name='valor mínimo')),
                ('max_value', models.PositiveSmallIntegerField(verbose_name='valor máximo')),
            ],
            options={
                'verbose_name': 'escala de avaliação',
                'verbose_name_plural': 'escala de avaliação',
                'ordering': ['level'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_value__lte', models.F('max_value'))), name='grading_gradingscale_min_lte_max')],
            },
        ),
        migrations.RunPython(load_grading_scale_fixture, unload_grading_scale_fixture),
    ]
