# Generated by Django 5.2.17 on 2026-09-18 19:43

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_schedule'),
        ('core', '0006_institution_description'),
        ('enrollment', '0005_student_admitted_from_candidate'),
        ('grading', '0002_gradingscale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('value', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='classificação')),
                ('is_grade_report_closed', models.BooleanField(default=False, help_text='RF-AVAL-04: impede edição sem autorização quando activo.', verbose_name='pauta fechada')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.academicterm', verbose_name='período lectivo')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.academicyear', verbose_name='ano lectivo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.course', verbose_name='curso')),
                ('curricular_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.curricularyear', verbose_name='ano curricular')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.academiccycle', verbose_name='ciclo lectivo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.department', verbose_name='departamento')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='enrollment.enrollment', verbose_name='matrícula')),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='grading.evaluationtype', verbose_name='tipo de avaliação')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.schoolclass', verbose_name='turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='enrollment.student', verbose_name='aluno')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.subject', verbose_name='disciplina')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_launched', to=settings.AUTH_USER_MODEL, verbose_name='docente lançador')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['-academic_year', 'school_class', 'subject', 'student'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['institution', 'is_deleted'], name='grading_gra_institu_43b499_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'academic_term', 'evaluation_type'), name='grading_grade_unique_per_student_subject_term_type')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
