# Generated by Django 5.2.17 on 2026-09-18 20:12

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_schedule'),
        ('core', '0006_institution_description'),
        ('enrollment', '0005_student_admitted_from_candidate'),
        ('grading', '0003_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='média calculada')),
                ('manual_override_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='valor ajustado manualmente')),
                ('override_reason', models.TextField(blank=True, default='', verbose_name='justificação do ajuste')),
                ('overridden_at', models.DateTimeField(blank=True, null=True, verbose_name='ajustado em')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_grades', to='core.academicterm', verbose_name='período lectivo')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_grades', to='enrollment.enrollment', verbose_name='matrícula')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_grade_overrides', to=settings.AUTH_USER_MODEL, verbose_name='ajustado por')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_grades', to='academic.subject', verbose_name='disciplina')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'média final',
                'verbose_name_plural': 'médias finais',
                'ordering': ['-academic_term', 'enrollment', 'subject'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['institution', 'is_deleted'], name='grading_fin_institu_9cd962_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'subject', 'academic_term'), name='grading_finalgrade_unique_per_enrollment_subject_term')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
