# Generated by Django 5.2.17 on 2026-09-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_finalgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalgrade',
            options={'base_manager_name': 'all_objects', 'ordering': ['-academic_term__start_date', 'enrollment__student__last_name', 'subject__name'], 'verbose_name': 'média final', 'verbose_name_plural': 'médias finais'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'base_manager_name': 'all_objects', 'ordering': ['-academic_year__start_date', 'school_class__designation', 'subject__name', 'student__last_name', 'student__first_name'], 'verbose_name': 'nota', 'verbose_name_plural': 'notas'},
        ),
    ]
