# Generated by Django 5.2.17 on 2026-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_alter_finalgrade_options_alter_grade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='reopening_reason',
            field=models.TextField(blank=True, default='', help_text='RF-AVAL-04/§7.4: preenchida pela Direção Pedagógica sempre que reabre uma pauta já homologada (issue #60) -- fica também no histórico de auditoria (issue #140), junto de quem reabriu e quando.', verbose_name='justificação da reabertura'),
        ),
    ]
