# Generated by Django 5.2.17 on 2026-09-18 21:41

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_schedule'),
        ('core', '0007_institution_max_recoverable_subjects'),
        ('enrollment', '0005_student_admitted_from_candidate'),
        ('grading', '0006_grade_reopening_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSituation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('pending_recovery', 'Com disciplinas em atraso'), ('failed', 'Reprovado')], max_length=20, verbose_name='situação')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='calculada em')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_situation', to='enrollment.enrollment', verbose_name='matrícula')),
                ('failed_subjects', models.ManyToManyField(blank=True, related_name='final_situations_failed_in', to='academic.subject', verbose_name='disciplinas em atraso')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'situação final',
                'verbose_name_plural': 'situações finais',
                'ordering': ['-calculated_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['institution', 'is_deleted'], name='grading_fin_institu_d88959_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
