# Generated by Django 5.2.17 on 2026-09-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_academicterm_options'),
        ('grading', '0008_alter_finalgrade_options_alter_grade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgrade',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_grades', to='core.academicterm', verbose_name='trimestre'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.academicterm', verbose_name='trimestre'),
        ),
    ]
