# Generated by Django 5.2.17 on 2026-09-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_active',
            field=models.BooleanField(default=False, help_text='Whether TOTP two-factor authentication is enabled for this account. Mandatory for Institution Administrator, Super Administrator and Finance profiles -- see issue #25.'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('pt', 'Português'), ('umb', 'Umbundu'), ('kmb', 'Kimbundu'), ('kon', 'Kikongo'), ('cjk', 'Chokwe'), ('kua', 'Oshikwanyama')], default='pt', help_text='A personal interface preference, never an institution/node-wide setting -- RNF-LOC-07: two users at the same school can each use a different interface language at the same time.', max_length=8),
        ),
    ]
