# Generated by Django 5.2.17 on 2026-09-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_grading_formula_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_2fa_active',
        ),
    ]
