# Generated by Django 5.2.17 on 2026-09-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_is_2fa_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive failed login attempts since the last successful login or lockout (issue #26, RNF-SEC-02).'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked out until this moment (issue #26) -- empty means not locked. An Administrator can clear this early via the "Desbloquear conta(s) seleccionada(s)" Django Admin action.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this account has been locked out so far -- each further lockout is progressively longer (issue #26). Reset to 0 by a successful login or a manual Administrator unlock.'),
        ),
    ]
