# Generated by Django 5.2.17 on 2026-09-12 14:58

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models

# National reference data (RNF-LOC-05): available from the very first
# `migrate`, on every node, not something an operator loads separately. See
# scripts/generate_core_reference_fixtures.py for how these fixtures are
# generated.
REFERENCE_FIXTURES = [
    "provinces_municipalities",
    "mobile_operators",
    "document_types",
    "professions",
]


def load_reference_fixtures(apps, schema_editor):
    call_command("loaddata", *REFERENCE_FIXTURES, app_label="core")


def unload_reference_fixtures(apps, schema_editor):
    apps.get_model("core", "Municipality").objects.all().delete()
    apps.get_model("core", "Province").objects.all().delete()
    apps.get_model("core", "MobileOperator").objects.all().delete()
    apps.get_model("core", "IdentificationDocumentType").objects.all().delete()
    apps.get_model("core", "Profession").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDocumentType',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MobileOperator',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalities', to='core.province')),
            ],
            options={
                'ordering': ['province__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('province', 'name'), name='core_municipality_unique_per_province')],
            },
        ),
        migrations.RunPython(load_reference_fixtures, unload_reference_fixtures),
    ]
