# Generated by Django 5.2.17 on 2026-09-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='africell_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefone Africell'),
        ),
        migrations.AddField(
            model_name='institution',
            name='blocks_documents_with_outstanding_debt',
            field=models.BooleanField(default=False, help_text='Parametrização financeira (RF-FIN-06).', verbose_name='bloqueia documentos com dívida'),
        ),
        migrations.AddField(
            model_name='institution',
            name='default_grading_formula',
            field=models.JSONField(blank=True, default=dict, help_text='Fórmula por omissão de cálculo de médias, sobreponível por curso/disciplina.', verbose_name='fórmula de média por omissão'),
        ),
        migrations.AddField(
            model_name='institution',
            name='district_or_commune',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='distrito/comuna'),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='institution',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='número da casa'),
        ),
        migrations.AddField(
            model_name='institution',
            name='landline_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefone fixo'),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name='logótipo'),
        ),
        migrations.AddField(
            model_name='institution',
            name='ministry_of_education_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='código MED'),
        ),
        migrations.AddField(
            model_name='institution',
            name='movicel_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefone Movicel'),
        ),
        migrations.AddField(
            model_name='institution',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='core.municipality', verbose_name='município'),
        ),
        migrations.AddField(
            model_name='institution',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='institution',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='core.province', verbose_name='província'),
        ),
        migrations.AddField(
            model_name='institution',
            name='street',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='rua'),
        ),
        migrations.AddField(
            model_name='institution',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='institution',
            name='unitel_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefone Unitel'),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
