# Generated by Django 5.2.17 on 2026-09-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academicyear_academicterm_nonteachingday_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='academiccycle',
            new_name='core_academ_institu_b6c182_idx',
            old_name='core_academiccycle_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='academicterm',
            new_name='core_academ_institu_e2582f_idx',
            old_name='core_academicterm_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='academicyear',
            new_name='core_academ_institu_a59c87_idx',
            old_name='core_academicyear_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='nonteachingday',
            new_name='core_nontea_institu_14c30e_idx',
            old_name='core_nonteachingday_tenant_idx',
        ),
    ]
