# Generated by Django 5.2.17 on 2026-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_academiccycle_tenant_idx_core_academ_institu_b6c182_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Apresentação/missão institucional (RF-PUB-01, issue #100) -- mostrada na página pública, editável por agora via Django Admin até existir uma UI dedicada (issue #114).', verbose_name='apresentação'),
        ),
    ]
