# Generated by Django 5.2.17 on 2026-09-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_institution_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='max_recoverable_subjects',
            field=models.PositiveSmallIntegerField(default=2, help_text='RF-AVAL-07/issue #62: acima deste número de disciplinas com média inferior a 10 valores, a situação final passa de "com disciplinas em atraso" (RF-AVAL-06\'s avaliação de recurso) a "reprovado". O Anexo III do RAA (Decreto Executivo 106/26), que fixaria este valor oficialmente, ainda não foi obtido -- ver docs/legislacao/escala-avaliacao-secundario.md. "2" é o valor mais comummente citado em escolas angolanas, não um valor normativo confirmado -- fica como ponto de partida editável pelo Administrador da Instituição.', verbose_name='máximo de disciplinas em atraso recuperáveis'),
        ),
    ]
