# Generated by Django 5.2.17 on 2026-09-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution_max_recoverable_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicterm',
            options={'base_manager_name': 'all_objects', 'ordering': ['academic_year', 'number'], 'verbose_name': 'trimestre', 'verbose_name_plural': 'trimestres'},
        ),
    ]
