# Generated by Django 5.2.17 on 2026-09-19 06:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_academicterm_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='absence_limit_weekly_load_multiplier',
            field=models.DecimalField(decimal_places=1, default=Decimal('3'), help_text="RF-FREQ-03/issue #175: o limite de faltas injustificadas de uma disciplina é este valor multiplicado pela sua carga horária semanal (`Subject.weekly_hours`). '3' é o valor fixado no Decreto Presidencial 162/23 (ver docs/legislacao/README.md) -- valor por omissão que reflecte a legislação vigente, mantido configurável por instituição caso um diploma futuro o altere.", max_digits=3, verbose_name='multiplicador do limite legal de faltas'),
        ),
    ]
