# Generated by Django 5.2.17 on 2026-09-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_institution_absence_limit_weekly_load_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='document_header_text',
            field=models.CharField(blank=True, default='', help_text='Linha adicional mostrada por baixo do nome da instituição no cabeçalho de todo documento oficial (pauta, boletim, declaração, comprovativo) -- ex. "República de Angola -- Ministério da Educação". Em branco, essa linha não aparece.', max_length=255, verbose_name='texto do cabeçalho dos documentos'),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_legal_footer_text',
            field=models.TextField(blank=True, default='', help_text='Texto legal (ex. registo/licenciamento, isenções, avisos normativos) mostrado no rodapé de todo documento oficial, por baixo da numeração/série. Em branco, o rodapé mostra só a numeração/série e o emissor, como antes desta configuração existir.', verbose_name='texto legal do rodapé dos documentos'),
        ),
    ]
