# Generated by Django 5.2.17 on 2026-09-19 09:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_institution_document_header_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admission_exam_passing_score',
            field=models.DecimalField(decimal_places=1, default=Decimal('10'), help_text="Nota mínima (escala 0-20) na prova de aptidão para um Candidato poder ser admitido à Inscrição, quando essa prova é exigida. '10' por omissão -- a mesma nota mínima de aprovação já usada na avaliação escolar (docs/legislacao/escala-avaliacao-secundario.md).", max_digits=4, verbose_name='nota mínima de aptidão na admissão'),
        ),
    ]
