# Generated by Django 5.2.17 on 2026-09-18 02:02

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_rename_core_academiccycle_tenant_idx_core_academ_institu_b6c182_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='nome completo')),
                ('kinship', models.CharField(choices=[('father', 'Pai'), ('mother', 'Mãe'), ('tutor', 'Tutor'), ('other', 'Outro')], max_length=10, verbose_name='grau de parentesco')),
                ('document_number', models.CharField(max_length=50, verbose_name='número do documento')),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='telemóvel')),
                ('landline_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone fixo')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('profession', models.CharField(blank=True, default='', max_length=100, verbose_name='profissão')),
                ('district_or_commune', models.CharField(blank=True, default='', max_length=100, verbose_name='distrito/comuna')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=100, verbose_name='bairro')),
                ('street', models.CharField(blank=True, default='', max_length=150, verbose_name='rua')),
                ('house_number', models.CharField(blank=True, default='', max_length=20, verbose_name='número da casa')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='core.identificationdocumenttype', verbose_name='tipo de documento')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='core.municipality', verbose_name='município')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='core.province', verbose_name='província')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Conta de acesso ao portal do Encarregado de Educação (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'encarregado de educação',
                'verbose_name_plural': 'encarregados de educação',
                'ordering': ['full_name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('student_number', models.PositiveIntegerField(editable=False, help_text='Sequencial por instituição.', verbose_name='número de aluno')),
                ('first_name', models.CharField(max_length=100, verbose_name='nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=10, verbose_name='género')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='foto')),
                ('document_number', models.CharField(max_length=50, verbose_name='número do documento')),
                ('document_issue_date', models.DateField(verbose_name='data de emissão do documento')),
                ('document_issue_place', models.CharField(help_text='Ex.: "Nacional - Luanda".', max_length=100, verbose_name='local de emissão do documento')),
                ('district_or_commune', models.CharField(blank=True, default='', max_length=100, verbose_name='distrito/comuna')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=100, verbose_name='bairro')),
                ('street', models.CharField(blank=True, default='', max_length=150, verbose_name='rua')),
                ('house_number', models.CharField(blank=True, default='', max_length=20, verbose_name='número da casa')),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='telemóvel')),
                ('landline_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone fixo')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='data de inscrição')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('transferred', 'Transferido'), ('completed', 'Concluído'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.identificationdocumenttype', verbose_name='tipo de documento')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.municipality', verbose_name='município')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.profession', verbose_name='profissão')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.province', verbose_name='província')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Contacto principal (financeiro/comunicação).', verbose_name='encarregado principal')),
                ('financially_responsible', models.BooleanField(default=False, verbose_name='responsável financeiro')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='enrollment.guardian', verbose_name='encarregado')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='enrollment.student', verbose_name='aluno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'encarregado do aluno',
                'verbose_name_plural': 'encarregados do aluno',
                'ordering': ['student', '-is_primary'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['institution', 'is_deleted'], name='enrollment__institu_a7fadf_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution', 'is_deleted'], name='enrollment__institu_8a5c76_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('institution', 'student_number'), name='enrollment_student_unique_number_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('institution', 'document_type', 'document_number'), name='enrollment_student_unique_document_per_institution'),
        ),
        migrations.AddIndex(
            model_name='studentguardian',
            index=models.Index(fields=['institution', 'is_deleted'], name='enrollment__institu_9e5631_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='enrollment_studentguardian_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='enrollment_studentguardian_one_primary_per_student'),
        ),
    ]
