# Generated by Django 5.2.17 on 2026-09-18 02:09

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('core', '0005_rename_core_academiccycle_tenant_idx_core_academ_institu_b6c182_idx_and_more'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='nome completo')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('contact', models.CharField(max_length=100, verbose_name='contacto')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('admitted', 'Admitido'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='estado')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='data de candidatura')),
                ('desired_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='academic.course', verbose_name='curso pretendido')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidatos',
                'ordering': ['-application_date'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['institution', 'is_deleted'], name='enrollment__institu_805197_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('enrollment_number', models.PositiveIntegerField(editable=False, help_text='Sequencial por instituição e ano lectivo.', verbose_name='número de matrícula')),
                ('date', models.DateField(auto_now_add=True, verbose_name='data')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Activa'), ('cancelled', 'Anulada'), ('transferred', 'Transferida'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='estado da matrícula')),
                ('presented_document_number', models.CharField(max_length=50, verbose_name='número do documento apresentado')),
                ('document_issue_date', models.DateField(verbose_name='data de emissão do documento')),
                ('document_issue_place', models.CharField(max_length=100, verbose_name='local de emissão do documento')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('is_repeating', models.BooleanField(default=False, verbose_name='é repetente')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.academicyear', verbose_name='ano lectivo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.course', verbose_name='curso')),
                ('curricular_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.curricularyear', verbose_name='ano curricular')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.academiccycle', verbose_name='ciclo lectivo')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('presented_document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.identificationdocumenttype', verbose_name='tipo de documento apresentado')),
                ('previous_enrollment', models.ForeignKey(blank=True, help_text='Referência à matrícula do ano anterior (histórico/retenção).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_enrollments', to='enrollment.enrollment', verbose_name='matrícula anterior')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.schoolclass', verbose_name='turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='enrollment.student', verbose_name='aluno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'matrícula',
                'verbose_name_plural': 'matrículas',
                'ordering': ['-academic_year', '-enrollment_number'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['institution', 'is_deleted'], name='enrollment__institu_42f8ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'academic_year', 'enrollment_number'), name='enrollment_enrollment_unique_number_per_institution_year')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
