# Generated by Django 5.2.17 on 2026-09-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_candidate_document_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admitted_from_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='enrollment.candidate', verbose_name='candidato de origem'),
        ),
    ]
