# Generated by Django 5.2.17 on 2026-09-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_student_admitted_from_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'base_manager_name': 'all_objects', 'ordering': ['first_name', 'last_name'], 'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
    ]
