# Generated by Django 5.2.17 on 2026-09-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', help_text='Issue #51/docs/06 §6.4: obrigatório ao anular (Estado = Anulada), vazio até lá.', verbose_name='motivo da anulação'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='previous_enrollment',
            field=models.ForeignKey(blank=True, help_text='Referência à matrícula do ano anterior (histórico/retenção/transferência).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_enrollments', to='enrollment.enrollment', verbose_name='matrícula anterior'),
        ),
    ]
