# Generated by Django 5.2.17 on 2026-09-19 07:26

import apps.core.fields
from django.db import migrations

from apps.core.crypto import encrypt_deterministic

ENCRYPTED_FIELDS = ["document_number", "mobile_phone", "landline_phone", "email"]

GUARDIAN_TABLE = "enrollment_guardian"


def encrypt_existing_guardian_data(apps, schema_editor):
    """Runs *after* the `AlterField`s below, once `enrollment_guardian`'s
    columns are already widened to fit ciphertext (see
    `apps.core.fields.EncryptedFieldMixin.db_type`) -- but the data sitting
    in them is still the original plaintext from before issue #141.

    Deliberately bypasses the ORM (`apps.get_model()`/`Guardian.objects`)
    and goes through a raw cursor instead: by this point in the migration,
    Django's own state already considers `document_number` etc. an
    `EncryptedCharField`, so reading a row the normal way would call
    `from_db_value` and try (and fail) to decrypt values that are not
    ciphertext yet. Only after this function runs are they.
    """
    table = schema_editor.connection.ops.quote_name(GUARDIAN_TABLE)
    columns = [schema_editor.connection.ops.quote_name(f) for f in ["id", *ENCRYPTED_FIELDS]]
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT {', '.join(columns)} FROM {table}")  # noqa: S608
        rows = cursor.fetchall()

        set_clause = ", ".join(f"{schema_editor.connection.ops.quote_name(f)} = %s" for f in ENCRYPTED_FIELDS)
        for pk, *values in rows:
            encrypted_values = [encrypt_deterministic(value) if value else value for value in values]
            cursor.execute(
                f"UPDATE {table} SET {set_clause} WHERE {schema_editor.connection.ops.quote_name('id')} = %s",  # noqa: S608
                [*encrypted_values, pk],
            )


def decrypt_existing_guardian_data(apps, schema_editor):
    # Reverse of the above, for `migrate enrollment 0007`. Deliberately not
    # implemented: downgrading past this migration is not a supported path
    # once real institution data has been encrypted -- a lost/rotated key
    # makes ciphertext permanently unrecoverable, by design (see
    # apps/core/crypto.py), so there is no safe, generic way to guarantee
    # the key used to encrypt is still the one configured when reversing.
    # Raising here also protects against the `AlterField`s below silently
    # narrowing the columns back and truncating still-encrypted data --
    # this runs first, since `RunPython` is the last operation below and
    # migrations reverse in the opposite order they were applied.
    raise NotImplementedError(
        "Não é possível reverter esta migração: os dados já cifrados de "
        "Guardian ficariam ilegíveis (ou seriam truncados) ao reverter para "
        "CharField simples (ver apps/core/crypto.py)."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_enrollment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='document_number',
            field=apps.core.fields.EncryptedCharField(max_length=50, verbose_name='número do documento'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='email',
            field=apps.core.fields.EncryptedEmailField(blank=True, default='', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='landline_phone',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=20, verbose_name='telefone fixo'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='mobile_phone',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=20, verbose_name='telemóvel'),
        ),
        migrations.RunPython(encrypt_existing_guardian_data, decrypt_existing_guardian_data),
    ]
