# Generated by Django 5.2.17 on 2026-09-19 08:52

from django.conf import settings
from django.db import migrations, models

ACTIVE_STATUSES = ["pending", "active"]


def cancel_duplicate_active_enrollments(apps, schema_editor):
    """Resolve, before the constraint below can even be added, any
    (institution, student, academic_year) group that already has more
    than one Pendente/Activa `Enrollment` -- a real duplicate found live
    (see the GitHub issue this migration closes out): the most recently
    created one in each group is kept, every earlier one is cancelled
    with an auditable reason, never deleted."""
    Enrollment = apps.get_model("enrollment", "Enrollment")

    conflicting_keys = (
        Enrollment.objects.filter(status__in=ACTIVE_STATUSES)
        .values("institution_id", "student_id", "academic_year_id")
        .annotate(models.Count("id"))
        .filter(id__count__gt=1)
    )
    for key in conflicting_keys:
        group = list(
            Enrollment.objects.filter(
                institution_id=key["institution_id"],
                student_id=key["student_id"],
                academic_year_id=key["academic_year_id"],
                status__in=ACTIVE_STATUSES,
            ).order_by("-created_at")
        )
        for duplicate in group[1:]:
            duplicate.status = "cancelled"
            duplicate.cancellation_reason = (
                "Anulada automaticamente pela migração "
                "0009_enrollment_enrollment_enrollment_one_active_per_student_per_year: "
                "este aluno tinha mais do que uma matrícula activa no mesmo ano lectivo "
                f"(mantida a mais recente, #{group[0].enrollment_number})."
            )
            duplicate.save(update_fields=["status", "cancellation_reason"])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_schoolclass_academic_term_alter_subject_term'),
        ('core', '0010_institution_document_header_text_and_more'),
        ('enrollment', '0008_alter_guardian_document_number_alter_guardian_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(cancel_duplicate_active_enrollments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('institution', 'student', 'academic_year'), name='enrollment_enrollment_one_active_per_student_per_year', violation_error_message='Este aluno já tem uma matrícula activa neste ano lectivo.'),
        ),
    ]
