# Generated by Django 5.2.17 on 2026-09-19 09:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_enrollment_enrollment_enrollment_one_active_per_student_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Escala 0-20 (a mesma da avaliação escolar) -- preenchida depois da prova de aptidão, só quando esta é exigida. Em branco: nenhuma prova foi exigida a este candidato.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='nota da prova de aptidão'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('admitted', 'Admitido'), ('rejected', 'Rejeitado'), ('second_call', 'Segunda Chamada')], default='pending', max_length=15, verbose_name='estado'),
        ),
    ]
