# Generated by Django 5.2.17 on 2026-09-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_candidate_exam_score_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceite (aguarda Inscrição)'), ('admitted', 'Admitido'), ('rejected', 'Rejeitado'), ('second_call', 'Segunda Chamada')], default='pending', max_length=15, verbose_name='estado'),
        ),
    ]
