# Generated by Django 5.2.17 on 2026-09-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_alter_candidate_status'),
        ('reports', '0002_alter_issueddocument_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='application_receipt',
            field=models.ForeignKey(blank=True, help_text="Número/série já reservado por apps.reports.services._reserve_document_number -- guardado aqui (issue #102) para que 'voltar a emitir' reimprima sempre o mesmo número em vez de reservar um novo a cada reimpressão.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reports.issueddocument', verbose_name='comprovativo de candidatura'),
        ),
    ]
