# Generated by Django 5.2.17 on 2026-09-18 01:48

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_rename_core_academiccycle_tenant_idx_core_academ_institu_b6c182_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(max_length=20, verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('abbreviation', models.CharField(blank=True, default='', max_length=20, verbose_name='abreviatura')),
                ('created_on', models.DateField(verbose_name='data de criação')),
                ('ministry_of_education_code', models.CharField(blank=True, default='', max_length=50, verbose_name='código MED')),
                ('duration_years', models.PositiveSmallIntegerField(help_text='Ex.: 4 anos (10.ª a 13.ª classe).', verbose_name='duração (anos)')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.academiccycle', verbose_name='ciclo')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CurricularYear',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('number', models.PositiveSmallIntegerField(verbose_name='número')),
                ('equivalent_grade', models.CharField(help_text='Ex.: "10.ª classe".', max_length=50, verbose_name='classe equivalente')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricular_years', to='academic.course', verbose_name='curso')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ano curricular',
                'verbose_name_plural': 'anos curriculares',
                'ordering': ['course', 'number'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academic.department', verbose_name='departamento'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('designation', models.CharField(max_length=100, verbose_name='designação')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='capacidade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['designation'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(max_length=20, verbose_name='código')),
                ('designation', models.CharField(max_length=100, verbose_name='designação')),
                ('max_enrollment', models.PositiveSmallIntegerField(default=36, verbose_name='número máximo de inscritos')),
                ('shift', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite')], max_length=10, verbose_name='turno')),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='core.academicterm', verbose_name='período lectivo')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='core.academicyear', verbose_name='ano lectivo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='academic.course', verbose_name='curso')),
                ('curricular_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='academic.curricularyear', verbose_name='ano curricular')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-academic_year', 'designation'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(max_length=20, verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('abbreviation', models.CharField(blank=True, default='', max_length=20, verbose_name='abreviatura')),
                ('created_on', models.DateField(verbose_name='data de criação')),
                ('subject_type', models.CharField(choices=[('mandatory', 'Obrigatória'), ('optional', 'Opcional'), ('extracurricular', 'Extracurricular')], max_length=20, verbose_name='tipo de disciplina')),
                ('weekly_hours', models.PositiveSmallIntegerField(verbose_name='carga horária semanal')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic.course', verbose_name='curso')),
                ('curricular_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic.curricularyear', verbose_name='ano curricular')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='core.academiccycle', verbose_name='ciclo')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('term', models.ForeignKey(blank=True, help_text='Apenas quando a disciplina é semestral/trimestral, não anual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='core.academicterm', verbose_name='período lectivo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['course', 'curricular_year', 'name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='curricularyear',
            index=models.Index(fields=['institution', 'is_deleted'], name='academic_cu_institu_0ce440_idx'),
        ),
        migrations.AddConstraint(
            model_name='curricularyear',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='academic_curricularyear_unique_number_per_course'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['institution', 'is_deleted'], name='academic_de_institu_4aff5e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institution', 'is_deleted'], name='academic_co_institu_8772d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='academic_course_unique_code_per_institution'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['institution', 'is_deleted'], name='academic_ro_institu_9a33d6_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['institution', 'is_deleted'], name='academic_sc_institu_8dbf4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('academic_year', 'code'), name='academic_schoolclass_unique_code_per_year'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['institution', 'is_deleted'], name='academic_su_institu_402208_idx'),
        ),
    ]
