# Generated by Django 5.2.17 on 2026-09-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_schedule'),
        ('core', '0008_alter_academicterm_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='core.academicterm', verbose_name='trimestre'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Apenas quando a disciplina é semestral/trimestral, não anual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='core.academicterm', verbose_name='trimestre'),
        ),
    ]
