# Generated by Django 5.2.17 on 2026-09-17 20:04

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_institution_africell_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(help_text='"app_label.model_name" da entidade alterada (ex. "grading.nota").', max_length=255, verbose_name='entidade')),
                ('entity_id', models.UUIDField(verbose_name='id da entidade')),
                ('operation', models.CharField(choices=[('create', 'Criação'), ('update', 'Actualização'), ('delete', 'Eliminação')], max_length=10, verbose_name='operação')),
                ('payload', models.JSONField(help_text='Estado da entidade após a alteração, serializado.', verbose_name='payload')),
                ('origin_node_id', models.UUIDField(help_text='O node onde esta alteração foi originalmente criada.', verbose_name='node de origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='NULL enquanto pendente de envio/aplicação.', null=True, verbose_name='sincronizado em')),
            ],
            options={
                'verbose_name': 'registo de alteração',
                'verbose_name_plural': 'registos de alteração',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['synced_at'], name='sync_changerecord_pending_idx'), models.Index(fields=['entity', 'entity_id'], name='sync_changerecord_entity_idx')],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('local', 'Nó Local'), ('central', 'Nó Central')], max_length=10, verbose_name='tipo')),
                ('public_key', models.TextField(help_text='Gerada no setup wizard da instalação e nunca reutilizada entre nós -- usada na autenticação mútua da sincronização (§8.5).', verbose_name='chave pública')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='última sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, help_text='Obrigatório para um Nó Local; um Nó Central agrega várias instituições.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='core.institution', verbose_name='instituição')),
            ],
            options={
                'verbose_name': 'node',
                'verbose_name_plural': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciada em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('status', models.CharField(choices=[('in_progress', 'Em curso'), ('succeeded', 'Concluída'), ('failed', 'Falhou')], default='in_progress', max_length=20, verbose_name='estado')),
                ('records_sent', models.PositiveIntegerField(default=0, verbose_name='registos enviados')),
                ('records_received', models.PositiveIntegerField(default=0, verbose_name='registos recebidos')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='erros')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_sessions', to='sync.node', verbose_name='node')),
            ],
            options={
                'verbose_name': 'sessão de sincronização',
                'verbose_name_plural': 'sessões de sincronização',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('institution__isnull', False), ('node_type', 'local')), models.Q(('institution__isnull', True), ('node_type', 'central')), _connector='OR'), name='sync_node_institution_matches_type', violation_error_message='Um Nó Local requer uma instituição; um Nó Central não tem uma fixa.'),
        ),
    ]
