# Generated by Django 5.2.17 on 2026-09-19 02:56

import apps.attendance.models.attendance_model
import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_alter_schoolclass_academic_term_alter_subject_term'),
        ('core', '0008_alter_academicterm_options'),
        ('enrollment', '0006_alter_student_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(verbose_name='data')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Falta'), ('justified_absent', 'Falta Justificada')], max_length=20, verbose_name='estado')),
                ('justification_text', models.TextField(blank=True, default='', verbose_name='justificação')),
                ('justification_attachment', models.FileField(blank=True, help_text='RF-FREQ-02/docs/09-seguranca-e-privacidade.md §9.3: nunca servido por URL pública directa -- acesso mediado por apps.attendance.views.justification_attachment_view.', null=True, upload_to=apps.attendance.models.attendance_model.justification_attachment_upload_to, verbose_name='anexo da justificação')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='enrollment.enrollment', verbose_name='matrícula')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records_registered', to=settings.AUTH_USER_MODEL, verbose_name='registado por')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academic.schedule', verbose_name='horário')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='enrollment.student', verbose_name='aluno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'presença',
                'verbose_name_plural': 'presenças',
                'ordering': ['-date', 'student__first_name', 'student__last_name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['institution', 'is_deleted'], name='attendance__institu_224dda_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'schedule', 'date'), name='unique_attendance_per_enrollment_schedule_date')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
