# Generated by Django 5.2.17 on 2026-09-18 07:32

import django.core.serializers.json
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Alteração'), ('delete', 'Eliminação')], max_length=10, verbose_name='acção')),
                ('entity', models.CharField(help_text='"app_label.ModelName", ex. "enrollment.Enrollment".', max_length=100, verbose_name='entidade')),
                ('entity_id', models.CharField(max_length=64, verbose_name='id da entidade')),
                ('values_before', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='valores antes')),
                ('values_after', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='valores depois')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
                ('user', models.ForeignKey(blank=True, help_text='Quem realizou a acção -- vazio para acções de sistema sem utilizador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'registo de auditoria',
                'verbose_name_plural': 'registos de auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='audit_audit_entity_e82e90_idx'), models.Index(fields=['user'], name='audit_audit_user_id_c5e26c_idx')],
            },
        ),
    ]
