# Generated by Django 5.2.17 on 2026-09-18 23:50

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_academicterm_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('document_type', models.CharField(max_length=50, verbose_name='tipo de documento')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='último número emitido')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sequência de documento',
                'verbose_name_plural': 'sequências de documento',
                'constraints': [models.UniqueConstraint(fields=('institution', 'document_type'), name='unique_document_sequence_per_institution_and_type')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IssuedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('origin_node_id', models.UUIDField(help_text='The node (local or central) where this record was originally created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('document_type', models.CharField(help_text='Identificador curto do tipo de documento, ex. "declaracao-matricula".', max_length=50, verbose_name='tipo de documento')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('formatted_number', models.CharField(help_text='Ex. "DECLARACAO-MATRICULA/2026/000123".', max_length=80, verbose_name='número/série')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.institution')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_documents', to=settings.AUTH_USER_MODEL, verbose_name='emitido por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento emitido',
                'verbose_name_plural': 'documentos emitidos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'formatted_number'), name='unique_issued_document_formatted_number_per_institution')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
