# Generated by Django 5.2.17 on 2026-09-19 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueddocument',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Em branco para documentos emitidos automaticamente pelo próprio sistema, sem nenhum funcionário envolvido -- ex. o comprovativo de candidatura de uma pré-candidatura pública (issue #102), que não passa por nenhum utilizador autenticado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_documents', to=settings.AUTH_USER_MODEL, verbose_name='emitido por'),
        ),
    ]
